this addaction ["Platoon Leader", "loadouts\bw_pl.sqf"];
this addaction ["Platoon FAC", "loadouts\bw_p_fac.sqf"];
this addaction ["Platoon Engineer (Demo)", "loadouts\bw_p_e_demo.sqf"];
this addaction ["Platoon Engineer (EOD)", "loadouts\bw_p_e_eod.sqf"];
this addaction ["Platoon Engineer (Fortification)", "loadouts\bw_p_e_fort.sqf"];
this addaction ["Platoon Engineer (Repair)", "loadouts\bw_p_e_rep.sqf"];
this addaction ["Platoon DMR", "loadouts\bw_p_dmr.sqf"];
this addaction ["Platoon Medic", "loadouts\bw_p_medic.sqf"];
this addaction ["Squad Leader", "loadouts\bw_sl.sqf"];
this addaction ["Combat Medic", "loadouts\bw_medic.sqf"];
this addaction ["Operator Rifle", "loadouts\bw_o_r.sqf"];
this addaction ["Operator AR", "loadouts\bw_o_ar.sqf"];
this addaction ["Operator Light AT", "loadouts\bw_o_lat.sqf"];
this addaction ["Operator MMG", "loadouts\bw_o_mmg.sqf"];
this addaction ["Operator Asst. MMG", "loadouts\bw_o_mmg_ab.sqf"];
this addaction ["Operator Medium AT", "loadouts\bw_o_mat.sqf"];
this addaction ["Operator Asst. Medium AT", "loadouts\bw_o_mat_ab.sqf"];
this addaction ["Operator Grenadier", "loadouts\bw_o_g.sqf"];
this addaction ["Operator DMR (5.56)", "loadouts\bw_o_dmr.sqf"];
this addaction ["Operator Battlerifle (G3)", "loadouts\bw_o_br.sqf"];
this addaction ["Operator Specialist (G36K)", "loadouts\bw_o_spc.sqf"];
this addaction ["Operator UAV", "loadouts\bw_o_uav.sqf"];
this addaction ["Operator Breacher", "loadouts\bw_o_breacher.sqf"];
this addaction ["Operator Engineer (Demo)", "loadouts\bw_o_e_demo.sqf"];
this addaction ["Operator Engineer (EOD)", "loadouts\bw_o_e_eod.sqf"];
this addaction ["Operator Engineer (Fortification)", "loadouts\bw_o_e_fort.sqf"];
this addaction ["Operator Engineer (Repair)", "loadouts\bw_o_e_rep.sqf"];
this addaction ["Fox Commander", "loadouts\bw_f_com.sqf"];
this addaction ["Fox Crewman", "loadouts\bw_f_crew.sqf"];
this addaction ["Fox Technician", "loadouts\bw_f_tech.sqf"];
