on: [push, workflow_dispatch]

jobs:

  get_mission_folders:
    runs-on: ubuntu-latest

    outputs:
        matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: lts/*
    - id: set-matrix
      run: |
        echo "::set-output name=matrix::{\"mission\":[\"[7R]COOP_KingoftheHill.Malden\"]}"

  build_missions:
    needs: get_mission_folders

    runs-on: ubuntu-latest

    strategy:
      matrix: ${{ fromJson(needs.get_mission_folders.outputs.matrix) }}

    steps:
    - uses: actions/checkout@v2
    - uses: team-gsri/actions-make-pbo@master
      with:
        mission: "${{ matrix.mission }}"
        briefingName: "${{ matrix.mission }}-${{ env.GITHUB_RUN_NUMBER }}"

    - uses: actions/upload-artifact@v2
      with:
        name: "${{ matrix.mission }}-${{ env.GITHUB_RUN_NUMBER }}.pbo"
        path: "${{ matrix.mission }}.pbo"
        retention-days: 1
