on: [push, workflow_dispatch]

jobs:

  get_mission_folders:
    runs-on: ubuntu-latest

    outputs:
        matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
    - uses: actions/checkout@v5
    - id: set-matrix
      run: |
        echo "matrix={\"mission\":$(ls -d */ | sed 's:/$::' | jq -R . | jq -s -c .)}" >> "$GITHUB_OUTPUT"

  build_missions:
    needs: get_mission_folders

    runs-on: ubuntu-latest

    strategy:
      matrix: ${{ fromJson(needs.get_mission_folders.outputs.matrix) }}

    steps:
    - uses: actions/checkout@v5
    - run: python3 .github/scripts/make_pbo.py "${{ matrix.mission }}" -o "${{ matrix.mission }}.pbo"

    - uses: actions/upload-artifact@v5
      with:
        name: ${{ matrix.mission }}.pbo
        path: ${{ github.workspace }}/*.pbo
        retention-days: 1
