on: [push, workflow_dispatch]

jobs:

  get_mission_folders:
    runs-on: ubuntu-latest

    outputs:
        matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: lts/*
    - id: set-matrix
      run: |
        echo "::set-output name=matrix::{\"mission\":$(node -r fs -p 'JSON.stringify(fs.readdirSync(".").filter((path) => !path.startsWith(".")))')}"

  build_missions:
    needs: get_mission_folders

    runs-on: ubuntu-latest

    strategy:
      matrix: ${{ fromJson(needs.get_mission_folders.outputs.matrix) }}

    steps:
    - uses: actions/checkout@v2
    - uses: team-gsri/actions-make-pbo@master
      with:
        mission: ${{ matrix.mission }}
        briefingName: ${{ matrix.mission }}-${{ github.run_number }}

    - run: ls -lahF
    - run: echo $PWD
    - run: echo "${{ matrix.mission }}"
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.mission }}.pbo
        path: ${{ github.workspace }}/*.pbo
        retention-days: 1
